package handlers

import "fizyo-platform/models"

// physiotherapistsData — 81 ilin tamamı için fake veri (her il 5 kayıt = 405 toplam)
var physiotherapistsData = []models.Physiotherapist{
	// 01 - Adana
	{ID: 1, Name: "Aylin Karadeniz", City: "Adana", District: "Seyhan", Phone: "0322 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 2, Name: "Burak Arslan", City: "Adana", District: "Çukurova", Phone: "0322 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 3, Name: "Cemile Yurt", City: "Adana", District: "Yüreğir", Phone: "0322 333 33 33", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 4, Name: "Doruk Şahin", City: "Adana", District: "Sarıçam", Phone: "0322 444 44 44", Specialties: []string{"Manuel Terapi", "Ortopedik Rehabilitasyon"}},
	{ID: 5, Name: "Eda Polat", City: "Adana", District: "Ceyhan", Phone: "0322 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 02 - Adıyaman
	{ID: 6, Name: "Fırat Çetin", City: "Adıyaman", District: "Merkez", Phone: "0416 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 7, Name: "Gizem Koç", City: "Adıyaman", District: "Kahta", Phone: "0416 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 8, Name: "Halil Aydın", City: "Adıyaman", District: "Besni", Phone: "0416 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 9, Name: "İpek Yılmaz", City: "Adıyaman", District: "Gölbaşı", Phone: "0416 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 10, Name: "Kaan Demir", City: "Adıyaman", District: "Merkez", Phone: "0416 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 03 - Afyonkarahisar
	{ID: 11, Name: "Lale Güneş", City: "Afyonkarahisar", District: "Merkez", Phone: "0272 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Manuel Terapi"}},
	{ID: 12, Name: "Mert Kaya", City: "Afyonkarahisar", District: "Sandıklı", Phone: "0272 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 13, Name: "Nihan Çelik", City: "Afyonkarahisar", District: "Dinar", Phone: "0272 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 14, Name: "Onur Tekin", City: "Afyonkarahisar", District: "Emirdağ", Phone: "0272 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 15, Name: "Pelin Arslan", City: "Afyonkarahisar", District: "İscehisar", Phone: "0272 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 04 - Ağrı
	{ID: 16, Name: "Rıza Doğan", City: "Ağrı", District: "Merkez", Phone: "0472 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 17, Name: "Seda Kılıç", City: "Ağrı", District: "Patnos", Phone: "0472 222 22 22", Specialties: []string{"Manuel Terapi"}},
	{ID: 18, Name: "Taner Yıldız", City: "Ağrı", District: "Doğubayazıt", Phone: "0472 333 33 33", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 19, Name: "Ufuk Şimşek", City: "Ağrı", District: "Tutak", Phone: "0472 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 20, Name: "Vildan Aksoy", City: "Ağrı", District: "Eleşkirt", Phone: "0472 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 05 - Amasya
	{ID: 21, Name: "Yiğit Öztürk", City: "Amasya", District: "Merkez", Phone: "0358 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 22, Name: "Zehra Bulut", City: "Amasya", District: "Suluova", Phone: "0358 222 22 22", Specialties: []string{"Pilates Terapisi"}},
	{ID: 23, Name: "Ali Keskin", City: "Amasya", District: "Merzifon", Phone: "0358 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 24, Name: "Banu Erdoğan", City: "Amasya", District: "Taşova", Phone: "0358 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 25, Name: "Cem Güler", City: "Amasya", District: "Gümüşhacıköy", Phone: "0358 555 55 55", Specialties: []string{"Manuel Terapi"}},
	// 06 - Ankara
	{ID: 26, Name: "Ahmet Yılmaz", City: "Ankara", District: "Çankaya", Phone: "0312 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 27, Name: "Ayşe Kaya", City: "Ankara", District: "Keçiören", Phone: "0312 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon", "Pediatrik Fizyoterapi"}},
	{ID: 28, Name: "Mehmet Demir", City: "Ankara", District: "Etimesgut", Phone: "0312 333 33 33", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	{ID: 29, Name: "Fatma Şahin", City: "Ankara", District: "Sincan", Phone: "0312 444 44 44", Specialties: []string{"Ortopedik Rehabilitasyon", "Manuel Terapi"}},
	{ID: 30, Name: "Sercan Çelik", City: "Ankara", District: "Mamak", Phone: "0312 555 55 55", Specialties: []string{"Spor Rehabilitasyonu"}},
	// 07 - Antalya
	{ID: 31, Name: "Volkan Tekin", City: "Antalya", District: "Muratpaşa", Phone: "0242 111 11 11", Specialties: []string{"Spor Rehabilitasyonu", "Ortopedik Rehabilitasyon"}},
	{ID: 32, Name: "Yasemin Öztürk", City: "Antalya", District: "Konyaaltı", Phone: "0242 222 22 22", Specialties: []string{"Pilates Terapisi"}},
	{ID: 33, Name: "Bora Keskin", City: "Antalya", District: "Kepez", Phone: "0242 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 34, Name: "Cansu Bulut", City: "Antalya", District: "Alanya", Phone: "0242 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 35, Name: "Deniz Kılıç", City: "Antalya", District: "Manavgat", Phone: "0242 555 55 55", Specialties: []string{"Manuel Terapi"}},
	// 08 - Artvin
	{ID: 36, Name: "Elif Avcı", City: "Artvin", District: "Merkez", Phone: "0466 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 37, Name: "Furkan Yalçın", City: "Artvin", District: "Hopa", Phone: "0466 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 38, Name: "Gülce Polat", City: "Artvin", District: "Borçka", Phone: "0466 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 39, Name: "Hüseyin Aydın", City: "Artvin", District: "Arhavi", Phone: "0466 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 40, Name: "İrem Güneş", City: "Artvin", District: "Şavşat", Phone: "0466 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 09 - Aydın
	{ID: 41, Name: "Jale Çetin", City: "Aydın", District: "Efeler", Phone: "0256 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 42, Name: "Kemal Doğan", City: "Aydın", District: "Kuşadası", Phone: "0256 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 43, Name: "Leyla Kılıç", City: "Aydın", District: "Didim", Phone: "0256 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 44, Name: "Murat Aksoy", City: "Aydın", District: "Söke", Phone: "0256 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 45, Name: "Nazlı Erdoğan", City: "Aydın", District: "Nazilli", Phone: "0256 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 10 - Balıkesir
	{ID: 46, Name: "Okan Şimşek", City: "Balıkesir", District: "Karesi", Phone: "0266 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 47, Name: "Pınar Güler", City: "Balıkesir", District: "Altıeylül", Phone: "0266 222 22 22", Specialties: []string{"Spor Yaralanmaları", "Manuel Terapi"}},
	{ID: 48, Name: "Recep Yıldız", City: "Balıkesir", District: "Bandırma", Phone: "0266 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 49, Name: "Sibel Çelik", City: "Balıkesir", District: "Edremit", Phone: "0266 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 50, Name: "Tolga Arslan", City: "Balıkesir", District: "Burhaniye", Phone: "0266 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 11 - Bilecik
	{ID: 51, Name: "Ümit Karadeniz", City: "Bilecik", District: "Merkez", Phone: "0228 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 52, Name: "Vildan Koç", City: "Bilecik", District: "Bozüyük", Phone: "0228 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 53, Name: "Yavuz Tekin", City: "Bilecik", District: "Osmaneli", Phone: "0228 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 54, Name: "Zeynep Bulut", City: "Bilecik", District: "Söğüt", Phone: "0228 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 55, Name: "Ahmet Keskin", City: "Bilecik", District: "Gölpazarı", Phone: "0228 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 12 - Bingöl
	{ID: 56, Name: "Bahar Yalçın", City: "Bingöl", District: "Merkez", Phone: "0426 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 57, Name: "Caner Polat", City: "Bingöl", District: "Genç", Phone: "0426 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 58, Name: "Derya Aydın", City: "Bingöl", District: "Solhan", Phone: "0426 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 59, Name: "Emrah Güneş", City: "Bingöl", District: "Kiğı", Phone: "0426 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 60, Name: "Filiz Çetin", City: "Bingöl", District: "Adaklı", Phone: "0426 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 13 - Bitlis
	{ID: 61, Name: "Görkem Kılıç", City: "Bitlis", District: "Merkez", Phone: "0434 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 62, Name: "Hande Aksoy", City: "Bitlis", District: "Tatvan", Phone: "0434 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 63, Name: "İlker Doğan", City: "Bitlis", District: "Ahlat", Phone: "0434 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 64, Name: "Jülide Erdoğan", City: "Bitlis", District: "Güroymak", Phone: "0434 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 65, Name: "Koray Şimşek", City: "Bitlis", District: "Hizan", Phone: "0434 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 14 - Bolu
	{ID: 66, Name: "Lara Güler", City: "Bolu", District: "Merkez", Phone: "0374 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 67, Name: "Melih Yıldız", City: "Bolu", District: "Gerede", Phone: "0374 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 68, Name: "Nilay Çelik", City: "Bolu", District: "Mudurnu", Phone: "0374 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 69, Name: "Osman Arslan", City: "Bolu", District: "Göynük", Phone: "0374 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 70, Name: "Pervin Karadeniz", City: "Bolu", District: "Seben", Phone: "0374 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 15 - Burdur
	{ID: 71, Name: "Ramazan Koç", City: "Burdur", District: "Merkez", Phone: "0248 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 72, Name: "Serap Tekin", City: "Burdur", District: "Bucak", Phone: "0248 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 73, Name: "Tolga Bulut", City: "Burdur", District: "Gölhisar", Phone: "0248 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 74, Name: "Ufuk Polat", City: "Burdur", District: "Tefenni", Phone: "0248 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 75, Name: "Vildan Aydın", City: "Burdur", District: "Yeşilova", Phone: "0248 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 16 - Bursa
	{ID: 76, Name: "Dilek Şimşek", City: "Bursa", District: "Nilüfer", Phone: "0224 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 77, Name: "Oğuz Polat", City: "Bursa", District: "Osmangazi", Phone: "0224 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 78, Name: "Pınar Yalçın", City: "Bursa", District: "Yıldırım", Phone: "0224 333 33 33", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 79, Name: "Serhan Güneş", City: "Bursa", District: "Gemlik", Phone: "0224 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 80, Name: "Tuba Aksoy", City: "Bursa", District: "Mudanya", Phone: "0224 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 17 - Çanakkale
	{ID: 81, Name: "Umut Kılıç", City: "Çanakkale", District: "Merkez", Phone: "0286 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 82, Name: "Venüs Erdoğan", City: "Çanakkale", District: "Biga", Phone: "0286 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 83, Name: "Yıldız Çetin", City: "Çanakkale", District: "Çan", Phone: "0286 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 84, Name: "Zafer Doğan", City: "Çanakkale", District: "Gelibolu", Phone: "0286 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 85, Name: "Aycan Güler", City: "Çanakkale", District: "Lapseki", Phone: "0286 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 18 - Çankırı
	{ID: 86, Name: "Barış Yıldız", City: "Çankırı", District: "Merkez", Phone: "0376 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 87, Name: "Ceylan Arslan", City: "Çankırı", District: "Çerkeş", Phone: "0376 222 22 22", Specialties: []string{"Manuel Terapi"}},
	{ID: 88, Name: "Dilan Karadeniz", City: "Çankırı", District: "Kurşunlu", Phone: "0376 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 89, Name: "Erkan Bulut", City: "Çankırı", District: "Ilgaz", Phone: "0376 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 90, Name: "Feride Koç", City: "Çankırı", District: "Atkaracalar", Phone: "0376 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 19 - Çorum
	{ID: 91, Name: "Gökhan Tekin", City: "Çorum", District: "Merkez", Phone: "0364 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 92, Name: "Hatice Polat", City: "Çorum", District: "Sungurlu", Phone: "0364 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 93, Name: "İbrahim Aydın", City: "Çorum", District: "Osmancık", Phone: "0364 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 94, Name: "Jale Güneş", City: "Çorum", District: "Alaca", Phone: "0364 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 95, Name: "Kenan Şimşek", City: "Çorum", District: "İskilip", Phone: "0364 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 20 - Denizli
	{ID: 96, Name: "Lerzan Kılıç", City: "Denizli", District: "Pamukkale", Phone: "0258 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 97, Name: "Mesut Erdoğan", City: "Denizli", District: "Merkezefendi", Phone: "0258 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 98, Name: "Nihal Çetin", City: "Denizli", District: "Acıpayam", Phone: "0258 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 99, Name: "Onur Aksoy", City: "Denizli", District: "Tavas", Phone: "0258 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 100, Name: "Petek Güler", City: "Denizli", District: "Honaz", Phone: "0258 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 21 - Diyarbakır
	{ID: 101, Name: "Rıfat Yıldız", City: "Diyarbakır", District: "Kayapınar", Phone: "0412 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 102, Name: "Selma Arslan", City: "Diyarbakır", District: "Bağlar", Phone: "0412 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 103, Name: "Tarkan Bulut", City: "Diyarbakır", District: "Yenişehir", Phone: "0412 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 104, Name: "Ülkü Koç", City: "Diyarbakır", District: "Ergani", Phone: "0412 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 105, Name: "Vedat Tekin", City: "Diyarbakır", District: "Bismil", Phone: "0412 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 22 - Edirne
	{ID: 106, Name: "Wafa Polat", City: "Edirne", District: "Merkez", Phone: "0284 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 107, Name: "Alp Kılıç", City: "Edirne", District: "Keşan", Phone: "0284 222 22 22", Specialties: []string{"Pilates Terapisi"}},
	{ID: 108, Name: "Yılmaz Güneş", City: "Edirne", District: "Uzunköprü", Phone: "0284 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 109, Name: "Zeliha Şimşek", City: "Edirne", District: "İpsala", Phone: "0284 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 110, Name: "Aslı Kaya", City: "Edirne", District: "Havsa", Phone: "0284 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 23 - Elazığ
	{ID: 111, Name: "Berke Erdoğan", City: "Elazığ", District: "Merkez", Phone: "0424 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 112, Name: "Ceren Aksoy", City: "Elazığ", District: "Kovancılar", Phone: "0424 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 113, Name: "Dinçer Güler", City: "Elazığ", District: "Karakoçan", Phone: "0424 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 114, Name: "Esra Yıldız", City: "Elazığ", District: "Keban", Phone: "0424 444 44 44", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 115, Name: "Fuat Arslan", City: "Elazığ", District: "Baskil", Phone: "0424 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 24 - Erzincan
	{ID: 116, Name: "Gamze Bulut", City: "Erzincan", District: "Merkez", Phone: "0446 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 117, Name: "Hayri Koç", City: "Erzincan", District: "Refahiye", Phone: "0446 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 118, Name: "Işıl Tekin", City: "Erzincan", District: "Tercan", Phone: "0446 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 119, Name: "Jale Polat", City: "Erzincan", District: "Kemah", Phone: "0446 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 120, Name: "Kamil Aydın", City: "Erzincan", District: "Üzümlü", Phone: "0446 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 25 - Erzurum
	{ID: 121, Name: "Latife Güneş", City: "Erzurum", District: "Yakutiye", Phone: "0442 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 122, Name: "Mahsun Şimşek", City: "Erzurum", District: "Palandöken", Phone: "0442 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 123, Name: "Neslihan Kılıç", City: "Erzurum", District: "Aziziye", Phone: "0442 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 124, Name: "Ozan Erdoğan", City: "Erzurum", District: "Horasan", Phone: "0442 444 44 44", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	{ID: 125, Name: "Pınar Aksoy", City: "Erzurum", District: "Tortum", Phone: "0442 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 26 - Eskişehir
	{ID: 126, Name: "Ruken Güler", City: "Eskişehir", District: "Odunpazarı", Phone: "0222 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 127, Name: "Savaş Yıldız", City: "Eskişehir", District: "Tepebaşı", Phone: "0222 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 128, Name: "Tülin Arslan", City: "Eskişehir", District: "Sivrihisar", Phone: "0222 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 129, Name: "Uğur Bulut", City: "Eskişehir", District: "Çifteler", Phone: "0222 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 130, Name: "Vildan Koç", City: "Eskişehir", District: "Mihalıççık", Phone: "0222 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 27 - Gaziantep
	{ID: 131, Name: "Yücel Tekin", City: "Gaziantep", District: "Şahinbey", Phone: "0342 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 132, Name: "Zehra Polat", City: "Gaziantep", District: "Şehitkamil", Phone: "0342 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 133, Name: "Aslan Aydın", City: "Gaziantep", District: "Nizip", Phone: "0342 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 134, Name: "Betül Güneş", City: "Gaziantep", District: "İslahiye", Phone: "0342 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 135, Name: "Cahit Şimşek", City: "Gaziantep", District: "Nurdağı", Phone: "0342 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 28 - Giresun
	{ID: 136, Name: "Duygu Kılıç", City: "Giresun", District: "Merkez", Phone: "0454 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 137, Name: "Ersin Erdoğan", City: "Giresun", District: "Bulancak", Phone: "0454 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 138, Name: "Funda Aksoy", City: "Giresun", District: "Espiye", Phone: "0454 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 139, Name: "Gürol Güler", City: "Giresun", District: "Tirebolu", Phone: "0454 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 140, Name: "Hülya Yıldız", City: "Giresun", District: "Görele", Phone: "0454 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 29 - Gümüşhane
	{ID: 141, Name: "İsmail Arslan", City: "Gümüşhane", District: "Merkez", Phone: "0456 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 142, Name: "Jale Bulut", City: "Gümüşhane", District: "Kelkit", Phone: "0456 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 143, Name: "Kıvanç Koç", City: "Gümüşhane", District: "Şiran", Phone: "0456 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 144, Name: "Lamia Tekin", City: "Gümüşhane", District: "Torul", Phone: "0456 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 145, Name: "Mahir Polat", City: "Gümüşhane", District: "Köse", Phone: "0456 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 30 - Hakkari
	{ID: 146, Name: "Nazan Aydın", City: "Hakkari", District: "Merkez", Phone: "0438 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 147, Name: "Orkan Güneş", City: "Hakkari", District: "Yüksekova", Phone: "0438 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 148, Name: "Pınar Şimşek", City: "Hakkari", District: "Çukurca", Phone: "0438 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 149, Name: "Rıfat Kılıç", City: "Hakkari", District: "Şemdinli", Phone: "0438 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 150, Name: "Sinem Erdoğan", City: "Hakkari", District: "Derecik", Phone: "0438 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 31 - Hatay
	{ID: 151, Name: "Tuncay Aksoy", City: "Hatay", District: "Antakya", Phone: "0326 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 152, Name: "Umay Güler", City: "Hatay", District: "İskenderun", Phone: "0326 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 153, Name: "Veda Yıldız", City: "Hatay", District: "Dörtyol", Phone: "0326 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 154, Name: "Volkan Arslan", City: "Hatay", District: "Kırıkhan", Phone: "0326 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 155, Name: "Yaren Bulut", City: "Hatay", District: "Samandağ", Phone: "0326 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 32 - Isparta
	{ID: 156, Name: "Zara Koç", City: "Isparta", District: "Merkez", Phone: "0246 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 157, Name: "Ahsen Tekin", City: "Isparta", District: "Yalvaç", Phone: "0246 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 158, Name: "Berk Polat", City: "Isparta", District: "Eğirdir", Phone: "0246 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 159, Name: "Canan Aydın", City: "Isparta", District: "Şarkikaraağaç", Phone: "0246 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 160, Name: "Davut Güneş", City: "Isparta", District: "Senirkent", Phone: "0246 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 33 - Mersin
	{ID: 161, Name: "Ebru Şimşek", City: "Mersin", District: "Yenişehir", Phone: "0324 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 162, Name: "Fikret Kılıç", City: "Mersin", District: "Mezitli", Phone: "0324 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 163, Name: "Gönül Erdoğan", City: "Mersin", District: "Toroslar", Phone: "0324 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 164, Name: "Hakan Aksoy", City: "Mersin", District: "Akdeniz", Phone: "0324 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 165, Name: "Işık Güler", City: "Mersin", District: "Tarsus", Phone: "0324 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 34 - İstanbul
	{ID: 166, Name: "Zeynep Arslan", City: "İstanbul", District: "Kadıköy", Phone: "0216 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 167, Name: "Emre Koç", City: "İstanbul", District: "Beşiktaş", Phone: "0212 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 168, Name: "Selin Aydın", City: "İstanbul", District: "Üsküdar", Phone: "0216 333 33 33", Specialties: []string{"Pediatrik Fizyoterapi", "Spor Yaralanmaları"}},
	{ID: 169, Name: "Burak Yıldız", City: "İstanbul", District: "Şişli", Phone: "0212 444 44 44", Specialties: []string{"Manuel Terapi", "Ortopedik Rehabilitasyon"}},
	{ID: 170, Name: "Ceren Doğan", City: "İstanbul", District: "Bakırköy", Phone: "0212 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 35 - İzmir
	{ID: 171, Name: "Hasan Özdemir", City: "İzmir", District: "Bornova", Phone: "0232 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 172, Name: "Merve Güler", City: "İzmir", District: "Konak", Phone: "0232 222 22 22", Specialties: []string{"Spor Yaralanmaları", "Pilates Terapisi"}},
	{ID: 173, Name: "Kerem Avcı", City: "İzmir", District: "Karşıyaka", Phone: "0232 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 174, Name: "Neslihan Kurt", City: "İzmir", District: "Çiğli", Phone: "0232 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 175, Name: "Tarık Erdoğan", City: "İzmir", District: "Buca", Phone: "0232 555 55 55", Specialties: []string{"Manuel Terapi"}},
	// 36 - Kars
	{ID: 176, Name: "Jale Şimşek", City: "Kars", District: "Merkez", Phone: "0474 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 177, Name: "Kadir Yıldız", City: "Kars", District: "Sarıkamış", Phone: "0474 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 178, Name: "Lale Arslan", City: "Kars", District: "Kağızman", Phone: "0474 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 179, Name: "Musa Bulut", City: "Kars", District: "Selim", Phone: "0474 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 180, Name: "Nesrin Koç", City: "Kars", District: "Arpaçay", Phone: "0474 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 37 - Kastamonu
	{ID: 181, Name: "Oğulcan Tekin", City: "Kastamonu", District: "Merkez", Phone: "0366 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 182, Name: "Pınar Polat", City: "Kastamonu", District: "Tosya", Phone: "0366 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 183, Name: "Rüştü Aydın", City: "Kastamonu", District: "Taşköprü", Phone: "0366 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 184, Name: "Sevinç Güneş", City: "Kastamonu", District: "Cide", Phone: "0366 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 185, Name: "Taylan Şimşek", City: "Kastamonu", District: "İnebolu", Phone: "0366 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 38 - Kayseri
	{ID: 186, Name: "Ufuk Kılıç", City: "Kayseri", District: "Kocasinan", Phone: "0352 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 187, Name: "Vahide Erdoğan", City: "Kayseri", District: "Melikgazi", Phone: "0352 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 188, Name: "Yücel Aksoy", City: "Kayseri", District: "Talas", Phone: "0352 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 189, Name: "Zerrin Güler", City: "Kayseri", District: "Develi", Phone: "0352 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 190, Name: "Alperen Yıldız", City: "Kayseri", District: "Hacılar", Phone: "0352 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 39 - Kırklareli
	{ID: 191, Name: "Burcu Arslan", City: "Kırklareli", District: "Merkez", Phone: "0288 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 192, Name: "Cengiz Bulut", City: "Kırklareli", District: "Lüleburgaz", Phone: "0288 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 193, Name: "Dilara Koç", City: "Kırklareli", District: "Babaeski", Phone: "0288 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 194, Name: "Egemen Tekin", City: "Kırklareli", District: "Vize", Phone: "0288 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 195, Name: "Feyza Polat", City: "Kırklareli", District: "Pınarhisar", Phone: "0288 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 40 - Kırşehir
	{ID: 196, Name: "Gürhan Aydın", City: "Kırşehir", District: "Merkez", Phone: "0386 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 197, Name: "Hacer Güneş", City: "Kırşehir", District: "Kaman", Phone: "0386 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 198, Name: "İlhan Şimşek", City: "Kırşehir", District: "Mucur", Phone: "0386 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 199, Name: "Jiyan Kılıç", City: "Kırşehir", District: "Çiçekdağı", Phone: "0386 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 200, Name: "Koray Erdoğan", City: "Kırşehir", District: "Akpınar", Phone: "0386 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 41 - Kocaeli
	{ID: 201, Name: "Lütfiye Aksoy", City: "Kocaeli", District: "İzmit", Phone: "0262 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 202, Name: "Mehmet Güler", City: "Kocaeli", District: "Gebze", Phone: "0262 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 203, Name: "Nilüfer Yıldız", City: "Kocaeli", District: "Körfez", Phone: "0262 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 204, Name: "Ozan Arslan", City: "Kocaeli", District: "Darıca", Phone: "0262 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 205, Name: "Pınar Bulut", City: "Kocaeli", District: "Dilovası", Phone: "0262 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 42 - Konya
	{ID: 206, Name: "Remzi Koç", City: "Konya", District: "Selçuklu", Phone: "0332 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 207, Name: "Sevgi Tekin", City: "Konya", District: "Karatay", Phone: "0332 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 208, Name: "Tamer Polat", City: "Konya", District: "Meram", Phone: "0332 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 209, Name: "Ülkü Aydın", City: "Konya", District: "Ereğli", Phone: "0332 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 210, Name: "Veysel Güneş", City: "Konya", District: "Akşehir", Phone: "0332 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 43 - Kütahya
	{ID: 211, Name: "Yasemin Şimşek", City: "Kütahya", District: "Merkez", Phone: "0274 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 212, Name: "Zekeriya Kılıç", City: "Kütahya", District: "Tavşanlı", Phone: "0274 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 213, Name: "Aylin Erdoğan", City: "Kütahya", District: "Simav", Phone: "0274 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 214, Name: "Bülent Aksoy", City: "Kütahya", District: "Gediz", Phone: "0274 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 215, Name: "Cansel Güler", City: "Kütahya", District: "Emet", Phone: "0274 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 44 - Malatya
	{ID: 216, Name: "Davut Yıldız", City: "Malatya", District: "Battalgazi", Phone: "0422 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 217, Name: "Emine Arslan", City: "Malatya", District: "Yeşilyurt", Phone: "0422 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 218, Name: "Faruk Bulut", City: "Malatya", District: "Doğanşehir", Phone: "0422 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 219, Name: "Gamze Koç", City: "Malatya", District: "Darende", Phone: "0422 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 220, Name: "Hüseyin Tekin", City: "Malatya", District: "Akçadağ", Phone: "0422 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 45 - Manisa
	{ID: 221, Name: "İnci Polat", City: "Manisa", District: "Şehzadeler", Phone: "0236 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 222, Name: "Jale Aydın", City: "Manisa", District: "Yunusemre", Phone: "0236 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 223, Name: "Kemal Güneş", City: "Manisa", District: "Akhisar", Phone: "0236 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 224, Name: "Lütfiye Şimşek", City: "Manisa", District: "Turgutlu", Phone: "0236 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 225, Name: "Mustafa Kılıç", City: "Manisa", District: "Salihli", Phone: "0236 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 46 - Kahramanmaraş
	{ID: 226, Name: "Nermin Erdoğan", City: "Kahramanmaraş", District: "Dulkadiroğlu", Phone: "0344 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 227, Name: "Orhan Aksoy", City: "Kahramanmaraş", District: "Onikişubat", Phone: "0344 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 228, Name: "Pınar Güler", City: "Kahramanmaraş", District: "Elbistan", Phone: "0344 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 229, Name: "Recep Yıldız", City: "Kahramanmaraş", District: "Afşin", Phone: "0344 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 230, Name: "Sibel Arslan", City: "Kahramanmaraş", District: "Pazarcık", Phone: "0344 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 47 - Mardin
	{ID: 231, Name: "Tahsin Bulut", City: "Mardin", District: "Artuklu", Phone: "0482 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 232, Name: "Ufuk Koç", City: "Mardin", District: "Kızıltepe", Phone: "0482 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 233, Name: "Veysel Tekin", City: "Mardin", District: "Midyat", Phone: "0482 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 234, Name: "Yıldız Polat", City: "Mardin", District: "Nusaybin", Phone: "0482 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 235, Name: "Zahide Aydın", City: "Mardin", District: "Derik", Phone: "0482 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 48 - Muğla
	{ID: 236, Name: "Alev Güneş", City: "Muğla", District: "Menteşe", Phone: "0252 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 237, Name: "Baran Şimşek", City: "Muğla", District: "Bodrum", Phone: "0252 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 238, Name: "Canan Kılıç", City: "Muğla", District: "Marmaris", Phone: "0252 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 239, Name: "Derviş Erdoğan", City: "Muğla", District: "Fethiye", Phone: "0252 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 240, Name: "Elif Aksoy", City: "Muğla", District: "Milas", Phone: "0252 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 49 - Muş
	{ID: 241, Name: "Faruk Güler", City: "Muş", District: "Merkez", Phone: "0436 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 242, Name: "Gülten Yıldız", City: "Muş", District: "Malazgirt", Phone: "0436 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 243, Name: "Hicran Arslan", City: "Muş", District: "Bulanık", Phone: "0436 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 244, Name: "İsmet Bulut", City: "Muş", District: "Varto", Phone: "0436 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 245, Name: "Janset Koç", City: "Muş", District: "Korkut", Phone: "0436 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 50 - Nevşehir
	{ID: 246, Name: "Kerem Tekin", City: "Nevşehir", District: "Merkez", Phone: "0384 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 247, Name: "Leyla Polat", City: "Nevşehir", District: "Ürgüp", Phone: "0384 222 22 22", Specialties: []string{"Pilates Terapisi"}},
	{ID: 248, Name: "Mete Aydın", City: "Nevşehir", District: "Avanos", Phone: "0384 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 249, Name: "Nesibe Güneş", City: "Nevşehir", District: "Gülşehir", Phone: "0384 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 250, Name: "Orçun Şimşek", City: "Nevşehir", District: "Hacıbektaş", Phone: "0384 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 51 - Niğde
	{ID: 251, Name: "Pelin Kılıç", City: "Niğde", District: "Merkez", Phone: "0388 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 252, Name: "Rıza Erdoğan", City: "Niğde", District: "Bor", Phone: "0388 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 253, Name: "Selin Aksoy", City: "Niğde", District: "Çamardı", Phone: "0388 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 254, Name: "Tülay Güler", City: "Niğde", District: "Ulukışla", Phone: "0388 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 255, Name: "Uğur Yıldız", City: "Niğde", District: "Altunhisar", Phone: "0388 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 52 - Ordu
	{ID: 256, Name: "Vesile Arslan", City: "Ordu", District: "Altınordu", Phone: "0452 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 257, Name: "Yağmur Bulut", City: "Ordu", District: "Ünye", Phone: "0452 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 258, Name: "Zeki Koç", City: "Ordu", District: "Fatsa", Phone: "0452 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 259, Name: "Ayhan Tekin", City: "Ordu", District: "Gürgentepe", Phone: "0452 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 260, Name: "Bircan Polat", City: "Ordu", District: "Perşembe", Phone: "0452 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 53 - Rize
	{ID: 261, Name: "Coşkun Aydın", City: "Rize", District: "Merkez", Phone: "0464 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 262, Name: "Duygu Güneş", City: "Rize", District: "Ardeşen", Phone: "0464 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 263, Name: "Erdal Şimşek", City: "Rize", District: "Pazar", Phone: "0464 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 264, Name: "Feriha Kılıç", City: "Rize", District: "Çayeli", Phone: "0464 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 265, Name: "Güven Erdoğan", City: "Rize", District: "İkizdere", Phone: "0464 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 54 - Sakarya
	{ID: 266, Name: "Hacer Aksoy", City: "Sakarya", District: "Adapazarı", Phone: "0264 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 267, Name: "İbrahim Güler", City: "Sakarya", District: "Serdivan", Phone: "0264 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 268, Name: "Jale Yıldız", City: "Sakarya", District: "Hendek", Phone: "0264 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 269, Name: "Kenan Arslan", City: "Sakarya", District: "Akyazı", Phone: "0264 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 270, Name: "Levent Bulut", City: "Sakarya", District: "Karasu", Phone: "0264 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 55 - Samsun
	{ID: 271, Name: "Mahinur Koç", City: "Samsun", District: "Atakum", Phone: "0362 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 272, Name: "Niyazi Tekin", City: "Samsun", District: "İlkadım", Phone: "0362 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 273, Name: "Olga Polat", City: "Samsun", District: "Canik", Phone: "0362 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 274, Name: "Pakize Aydın", City: "Samsun", District: "Bafra", Phone: "0362 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 275, Name: "Reha Güneş", City: "Samsun", District: "Vezirköprü", Phone: "0362 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 56 - Siirt
	{ID: 276, Name: "Saniye Şimşek", City: "Siirt", District: "Merkez", Phone: "0484 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 277, Name: "Tekin Kılıç", City: "Siirt", District: "Kurtalan", Phone: "0484 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 278, Name: "Ufuk Erdoğan", City: "Siirt", District: "Baykan", Phone: "0484 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 279, Name: "Veda Aksoy", City: "Siirt", District: "Pervari", Phone: "0484 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 280, Name: "Yetkin Güler", City: "Siirt", District: "Eruh", Phone: "0484 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 57 - Sinop
	{ID: 281, Name: "Zühal Yıldız", City: "Sinop", District: "Merkez", Phone: "0368 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 282, Name: "Adem Arslan", City: "Sinop", District: "Boyabat", Phone: "0368 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 283, Name: "Bahar Bulut", City: "Sinop", District: "Gerze", Phone: "0368 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 284, Name: "Cem Koç", City: "Sinop", District: "Durağan", Phone: "0368 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 285, Name: "Didem Tekin", City: "Sinop", District: "Ayancık", Phone: "0368 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 58 - Sivas
	{ID: 286, Name: "Engin Polat", City: "Sivas", District: "Merkez", Phone: "0346 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 287, Name: "Filiz Aydın", City: "Sivas", District: "Şarkışla", Phone: "0346 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 288, Name: "Gözde Güneş", City: "Sivas", District: "Suşehri", Phone: "0346 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 289, Name: "Hamit Şimşek", City: "Sivas", District: "Zara", Phone: "0346 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 290, Name: "Işılay Kılıç", City: "Sivas", District: "Gemerek", Phone: "0346 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 59 - Tekirdağ
	{ID: 291, Name: "Janset Erdoğan", City: "Tekirdağ", District: "Süleymanpaşa", Phone: "0282 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 292, Name: "Kürşat Aksoy", City: "Tekirdağ", District: "Çorlu", Phone: "0282 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 293, Name: "Lamia Güler", City: "Tekirdağ", District: "Çerkezköy", Phone: "0282 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 294, Name: "Mahmut Yıldız", City: "Tekirdağ", District: "Malkara", Phone: "0282 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 295, Name: "Nefise Arslan", City: "Tekirdağ", District: "Muratlı", Phone: "0282 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 60 - Tokat
	{ID: 296, Name: "Oktay Bulut", City: "Tokat", District: "Merkez", Phone: "0356 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 297, Name: "Pervin Koç", City: "Tokat", District: "Erbaa", Phone: "0356 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 298, Name: "Reşat Tekin", City: "Tokat", District: "Niksar", Phone: "0356 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 299, Name: "Sema Polat", City: "Tokat", District: "Turhal", Phone: "0356 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 300, Name: "Tarık Aydın", City: "Tokat", District: "Zile", Phone: "0356 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 61 - Trabzon
	{ID: 301, Name: "Umut Güneş", City: "Trabzon", District: "Ortahisar", Phone: "0462 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 302, Name: "Venüs Şimşek", City: "Trabzon", District: "Akçaabat", Phone: "0462 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 303, Name: "Yıldırım Kılıç", City: "Trabzon", District: "Araklı", Phone: "0462 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 304, Name: "Zeliha Erdoğan", City: "Trabzon", District: "Çaykara", Phone: "0462 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 305, Name: "Ahsen Aksoy", City: "Trabzon", District: "Of", Phone: "0462 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 62 - Tunceli
	{ID: 306, Name: "Barış Güler", City: "Tunceli", District: "Merkez", Phone: "0428 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 307, Name: "Ceyda Yıldız", City: "Tunceli", District: "Pertek", Phone: "0428 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 308, Name: "Doğan Arslan", City: "Tunceli", District: "Mazgirt", Phone: "0428 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 309, Name: "Esra Bulut", City: "Tunceli", District: "Hozat", Phone: "0428 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 310, Name: "Furkan Koç", City: "Tunceli", District: "Pülümür", Phone: "0428 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 63 - Şanlıurfa
	{ID: 311, Name: "Gülhan Tekin", City: "Şanlıurfa", District: "Karaköprü", Phone: "0414 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 312, Name: "Hidayet Polat", City: "Şanlıurfa", District: "Eyyübiye", Phone: "0414 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 313, Name: "Işıl Aydın", City: "Şanlıurfa", District: "Haliliye", Phone: "0414 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 314, Name: "Jale Güneş", City: "Şanlıurfa", District: "Siverek", Phone: "0414 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 315, Name: "Kıvanç Şimşek", City: "Şanlıurfa", District: "Viranşehir", Phone: "0414 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 64 - Uşak
	{ID: 316, Name: "Lale Kılıç", City: "Uşak", District: "Merkez", Phone: "0276 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 317, Name: "Mehmet Erdoğan", City: "Uşak", District: "Banaz", Phone: "0276 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 318, Name: "Nihan Aksoy", City: "Uşak", District: "Eşme", Phone: "0276 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 319, Name: "Oğuzhan Güler", City: "Uşak", District: "Karahallı", Phone: "0276 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 320, Name: "Pelin Yıldız", City: "Uşak", District: "Ulubey", Phone: "0276 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 65 - Van
	{ID: 321, Name: "Reşit Arslan", City: "Van", District: "İpekyolu", Phone: "0432 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 322, Name: "Songül Bulut", City: "Van", District: "Tuşba", Phone: "0432 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 323, Name: "Tarık Koç", City: "Van", District: "Edremit", Phone: "0432 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 324, Name: "Ümran Tekin", City: "Van", District: "Erciş", Phone: "0432 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 325, Name: "Veli Polat", City: "Van", District: "Özalp", Phone: "0432 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 66 - Yozgat
	{ID: 326, Name: "Yıldız Aydın", City: "Yozgat", District: "Merkez", Phone: "0354 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 327, Name: "Zeki Güneş", City: "Yozgat", District: "Sorgun", Phone: "0354 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 328, Name: "Ayhan Şimşek", City: "Yozgat", District: "Akdağmadeni", Phone: "0354 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 329, Name: "Burcu Kılıç", City: "Yozgat", District: "Yerköy", Phone: "0354 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 330, Name: "Cahit Erdoğan", City: "Yozgat", District: "Boğazlıyan", Phone: "0354 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 67 - Zonguldak
	{ID: 331, Name: "Demet Aksoy", City: "Zonguldak", District: "Merkez", Phone: "0372 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 332, Name: "Erdal Güler", City: "Zonguldak", District: "Ereğli", Phone: "0372 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 333, Name: "Fatma Yıldız", City: "Zonguldak", District: "Çaycuma", Phone: "0372 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 334, Name: "Gürkan Arslan", City: "Zonguldak", District: "Devrek", Phone: "0372 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 335, Name: "Hacer Bulut", City: "Zonguldak", District: "Alaplı", Phone: "0372 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 68 - Aksaray
	{ID: 336, Name: "İlker Koç", City: "Aksaray", District: "Merkez", Phone: "0382 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 337, Name: "Jale Tekin", City: "Aksaray", District: "Eskil", Phone: "0382 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 338, Name: "Kadriye Polat", City: "Aksaray", District: "Ortaköy", Phone: "0382 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 339, Name: "Levent Aydın", City: "Aksaray", District: "Ağaçören", Phone: "0382 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 340, Name: "Merve Güneş", City: "Aksaray", District: "Gülağaç", Phone: "0382 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 69 - Bayburt
	{ID: 341, Name: "Nuri Şimşek", City: "Bayburt", District: "Merkez", Phone: "0458 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 342, Name: "Oya Kılıç", City: "Bayburt", District: "Aydıntepe", Phone: "0458 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 343, Name: "Polat Erdoğan", City: "Bayburt", District: "Demirözü", Phone: "0458 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 344, Name: "Rabia Aksoy", City: "Bayburt", District: "Merkez", Phone: "0458 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 345, Name: "Sarp Güler", City: "Bayburt", District: "Merkez", Phone: "0458 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 70 - Karaman
	{ID: 346, Name: "Tuba Yıldız", City: "Karaman", District: "Merkez", Phone: "0338 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 347, Name: "Ufuk Arslan", City: "Karaman", District: "Ermenek", Phone: "0338 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 348, Name: "Veysel Bulut", City: "Karaman", District: "Kazımkarabekir", Phone: "0338 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 349, Name: "Wafa Koç", City: "Karaman", District: "Sarıveliler", Phone: "0338 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 350, Name: "Yılmaz Tekin", City: "Karaman", District: "Ayrancı", Phone: "0338 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 71 - Kırıkkale
	{ID: 351, Name: "Zehra Polat", City: "Kırıkkale", District: "Merkez", Phone: "0318 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 352, Name: "Altan Aydın", City: "Kırıkkale", District: "Yahşihan", Phone: "0318 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 353, Name: "Beren Güneş", City: "Kırıkkale", District: "Keskin", Phone: "0318 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 354, Name: "Cihan Şimşek", City: "Kırıkkale", District: "Sulakyurt", Phone: "0318 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 355, Name: "Dilara Kılıç", City: "Kırıkkale", District: "Balışeyh", Phone: "0318 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 72 - Batman
	{ID: 356, Name: "Emre Erdoğan", City: "Batman", District: "Merkez", Phone: "0488 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 357, Name: "Feyza Aksoy", City: "Batman", District: "Gercüş", Phone: "0488 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 358, Name: "Güven Güler", City: "Batman", District: "Beşiri", Phone: "0488 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 359, Name: "Hatice Yıldız", City: "Batman", District: "Sason", Phone: "0488 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 360, Name: "İbrahim Arslan", City: "Batman", District: "Kozluk", Phone: "0488 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 73 - Şırnak
	{ID: 361, Name: "Jale Bulut", City: "Şırnak", District: "Merkez", Phone: "0486 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 362, Name: "Kemal Koç", City: "Şırnak", District: "Cizre", Phone: "0486 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 363, Name: "Lale Tekin", City: "Şırnak", District: "Silopi", Phone: "0486 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 364, Name: "Mahsun Polat", City: "Şırnak", District: "İdil", Phone: "0486 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 365, Name: "Naciye Aydın", City: "Şırnak", District: "Uludere", Phone: "0486 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 74 - Bartın
	{ID: 366, Name: "Oğuz Güneş", City: "Bartın", District: "Merkez", Phone: "0378 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 367, Name: "Perihan Şimşek", City: "Bartın", District: "Amasra", Phone: "0378 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 368, Name: "Rıdvan Kılıç", City: "Bartın", District: "Kurucaşile", Phone: "0378 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 369, Name: "Serap Erdoğan", City: "Bartın", District: "Ulus", Phone: "0378 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 370, Name: "Tuncay Aksoy", City: "Bartın", District: "Merkez", Phone: "0378 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 75 - Ardahan
	{ID: 371, Name: "Ufuk Güler", City: "Ardahan", District: "Merkez", Phone: "0478 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 372, Name: "Vildan Yıldız", City: "Ardahan", District: "Göle", Phone: "0478 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 373, Name: "Yasin Arslan", City: "Ardahan", District: "Hanak", Phone: "0478 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 374, Name: "Zeynep Bulut", City: "Ardahan", District: "Çıldır", Phone: "0478 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 375, Name: "Alpay Koç", City: "Ardahan", District: "Damal", Phone: "0478 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 76 - Iğdır
	{ID: 376, Name: "Bülent Tekin", City: "Iğdır", District: "Merkez", Phone: "0476 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 377, Name: "Ceren Polat", City: "Iğdır", District: "Tuzluca", Phone: "0476 222 22 22", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 378, Name: "Davut Aydın", City: "Iğdır", District: "Aralık", Phone: "0476 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 379, Name: "Emine Güneş", City: "Iğdır", District: "Karakoyunlu", Phone: "0476 444 44 44", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 380, Name: "Faruk Şimşek", City: "Iğdır", District: "Merkez", Phone: "0476 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 77 - Yalova
	{ID: 381, Name: "Gizem Kılıç", City: "Yalova", District: "Merkez", Phone: "0226 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 382, Name: "Haluk Erdoğan", City: "Yalova", District: "Çınarcık", Phone: "0226 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 383, Name: "İpek Aksoy", City: "Yalova", District: "Altınova", Phone: "0226 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 384, Name: "Jale Güler", City: "Yalova", District: "Armutlu", Phone: "0226 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 385, Name: "Kenan Yıldız", City: "Yalova", District: "Termal", Phone: "0226 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 78 - Karabük
	{ID: 386, Name: "Leyla Arslan", City: "Karabük", District: "Merkez", Phone: "0370 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 387, Name: "Murat Bulut", City: "Karabük", District: "Safranbolu", Phone: "0370 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 388, Name: "Nilüfer Koç", City: "Karabük", District: "Eflani", Phone: "0370 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 389, Name: "Okan Tekin", City: "Karabük", District: "Ovacık", Phone: "0370 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 390, Name: "Pınar Polat", City: "Karabük", District: "Yenice", Phone: "0370 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
	// 79 - Kilis
	{ID: 391, Name: "Ramazan Aydın", City: "Kilis", District: "Merkez", Phone: "0348 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon"}},
	{ID: 392, Name: "Saadet Güneş", City: "Kilis", District: "Musabeyli", Phone: "0348 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 393, Name: "Tayfun Şimşek", City: "Kilis", District: "Polateli", Phone: "0348 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 394, Name: "Ülkü Kılıç", City: "Kilis", District: "Elbeyli", Phone: "0348 444 44 44", Specialties: []string{"Spor Yaralanmaları"}},
	{ID: 395, Name: "Volkan Erdoğan", City: "Kilis", District: "Merkez", Phone: "0348 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 80 - Osmaniye
	{ID: 396, Name: "Yılmaz Aksoy", City: "Osmaniye", District: "Merkez", Phone: "0328 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Pilates Terapisi"}},
	{ID: 397, Name: "Zehra Güler", City: "Osmaniye", District: "Kadirli", Phone: "0328 222 22 22", Specialties: []string{"Spor Rehabilitasyonu"}},
	{ID: 398, Name: "Ahmet Yıldız", City: "Osmaniye", District: "Düziçi", Phone: "0328 333 33 33", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 399, Name: "Banu Arslan", City: "Osmaniye", District: "Bahçe", Phone: "0328 444 44 44", Specialties: []string{"Manuel Terapi"}},
	{ID: 400, Name: "Caner Bulut", City: "Osmaniye", District: "Toprakkale", Phone: "0328 555 55 55", Specialties: []string{"Pediatrik Fizyoterapi"}},
	// 81 - Düzce
	{ID: 401, Name: "Derya Koç", City: "Düzce", District: "Merkez", Phone: "0380 111 11 11", Specialties: []string{"Ortopedik Rehabilitasyon", "Spor Yaralanmaları"}},
	{ID: 402, Name: "Efe Tekin", City: "Düzce", District: "Akçakoca", Phone: "0380 222 22 22", Specialties: []string{"Nörolojik Rehabilitasyon"}},
	{ID: 403, Name: "Figen Polat", City: "Düzce", District: "Gölyaka", Phone: "0380 333 33 33", Specialties: []string{"Manuel Terapi"}},
	{ID: 404, Name: "Güneş Aydın", City: "Düzce", District: "Kaynaşlı", Phone: "0380 444 44 44", Specialties: []string{"Pediatrik Fizyoterapi"}},
	{ID: 405, Name: "Hasan Güneş", City: "Düzce", District: "Cumayeri", Phone: "0380 555 55 55", Specialties: []string{"Kardiyopulmoner Rehabilitasyon"}},
}
